# Generated by Django 4.1.3 on 2022-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttr',
            new_name='ProductAttribute',
        ),
    ]
