# Generated by Django 4.1.3 on 2022-11-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_productattr_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='is_available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
