# Generated by Django 4.1.3 on 2022-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productattribute_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
