# Generated by Django 4.1.3 on 2022-11-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productattribute_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='image1',
            new_name='image',
        ),
    ]
