# Generated by Django 4.1.3 on 2022-11-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_image1_productattribute_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='image',
        ),
    ]
