# Generated by Django 4.1.3 on 2022-11-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_productattribute_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
