# Generated by Django 4.1.3 on 2022-11-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_pricefilter'),
        ('store', '0010_alter_product_image2_alter_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.pricefilter'),
        ),
    ]
