# Generated by Django 4.1.3 on 2022-11-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_caart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caart',
        ),
    ]
