# Generated by Django 4.1.3 on 2022-11-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_price_filter'),
        ('carts', '0002_remove_cart_created_at_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ManyToManyField(blank=True, to='store.productattribute'),
        ),
    ]
