# Generated by Django 4.1.3 on 2022-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0006_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="modify_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
