# Generated by Django 4.1.3 on 2022-11-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0007_coupon_created_date_coupon_expiry_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="is_expired",
        ),
        migrations.AddField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
