# Generated by Django 4.1.3 on 2022-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('500 TO 1000', '500 TO 1000'), ('1000 TO 2000', '1000 TO 2000'), ('2000 TO 5000', '2000 TO 5000'), ('5000 TO 10000', '5000 TO 10000')], max_length=60)),
            ],
        ),
    ]
