# Generated by Django 4.1.3 on 2022-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
