# Generated by Django 4.1.3 on 2022-11-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Processing", "Processing"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                ],
                default="None",
                max_length=10,
            ),
        ),
    ]
