# Generated by Django 4.1.3 on 2022-11-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_coupon_order_coupon_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon_discount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
